[buildPlans.iosevka-ss08]
family = "Iosevka ss08"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-ss08.variants]
  inherits = "ss08"

  [buildPlans.iosevka-ss08.metric-override]
  leading = 1110
  symbolMid = 280

[buildPlans.iosevka-ss08.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ss08.weights.bold]
shape = 700
menu = 700
css = 700


[buildPlans.iosevka-slab]
family = "Iosevka Slab"
spacing = "normal"
serifs = "slab"
no-cv-ss = true

  # [buildPlans.iosevka-slab.variants]
  # inherits = "ss08"

[buildPlans.iosevka-slab.variants.design]
asterisk = "penta-low"
underscore = "low"
brace = "straight"
number-sign = "slanted"
ampersand = "upper-open"
dollar = "open"
cent = "open"
percent = "dots"

  [buildPlans.iosevka-slab.metric-override]
  leading = 1110
  symbolMid = 280

# [buildPlans.iosevka-slab.weights.regular]
# shape = 400
# menu = 400
# css = 400

# [buildPlans.iosevka-slab.weights.bold]
# shape = 700
# menu = 700
# css = 700
